const script = `  CREATE TABLE tbluser (
  id TEXT DEFAULT to_char(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS') PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  firstname VARCHAR(50) NOT NULL,
  lastname VARCHAR(50),
  contact VARCHAR(20),
  accounts TEXT[],
  password TEXT,
  country TEXT,
  currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
)
  
CREATE TABLE tblaccount (
  id SERIAL NOT NULL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES tbluser(id),
  account_name VARCHAR(50) NOT NULL,
  account_number VARCHAR(50) NOT NULL UNIQUE,
  account_balance NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE tbltransaction (
  id SERIAL NOT NULL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES tbluser(id),
  description TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  source VARCHAR(100) NOT NULL,
  amount NUMERIC(15, 2) NOT NULL,
  type VARCHAR(20) NOT NULL DEFAULT 'income',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
);

`